run: 
	go run ./cmd/lavanderia/main.go

test:
	go test ./cmd/lavanderia \
			./internal/lavanderia/controllers \
			./internal/lavanderia/databases \
			./internal/lavanderia/repositories \
			./internal/lavanderia/handlers/business \
			./internal/lavanderia/handlers/auth