run: 
	go run ./cmd/lavanderia/main.go

test:
	go test ./cmd/lavanderia \
			./internal/lavanderia/controllers \
			./internal/lavanderia/databases \
			./internal/lavanderia/repositories \
			./internal/lavanderia/handlers/business \
			./internal/lavanderia/handlers/auth \
			./internal/lavanderia/handlers/product \
			./internal/lavanderia/handlers/client \
			./internal/lavanderia/handlers/address \
			./internal/lavanderia/handlers/delivery \
			./internal/lavanderia/handlers/order